################### Fabricbeat Configuration #########################


############################# Fabricbeat ######################################

fabricbeat:
  # Defines how often an event is sent to the output
  period: 1s
  # Defines which organization the connected peer is part of
  organization: org${ORG_NUMBER}
  # Defines the peer which fabricbeat should query
  peer: peer${PEER_NUMBER}.org${ORG_NUMBER}.el-network.com
  # Defines the location of the connection profile of the Fabric network
  connectionProfile: ${GOPATH}/src/github.com/hyperledger-elastic/network/${NETWORK}/connection-profile-${ORG_NUMBER}.yaml
  # Path to the admin certfile and keyfile
  adminCertPath: "${GOPATH}/src/github.com/hyperledger-elastic/network/${NETWORK}/crypto-config/peerOrganizations/org${ORG_NUMBER}.el-network.com/users/Admin@org${ORG_NUMBER}.el-network.com/msp/signcerts/Admin@org${ORG_NUMBER}.el-network.com-cert.pem"
  adminKeyPath: "${GOPATH}/src/github.com/hyperledger-elastic/network/${NETWORK}/crypto-config/peerOrganizations/org${ORG_NUMBER}.el-network.com/users/Admin@org${ORG_NUMBER}.el-network.com/msp/keystore/adminKey${ORG_NUMBER}"
  # URL of Elasticsearch
  elasticURL: "http://localhost:9200"
  # URL of Kibana
  kibanaURL: "http://localhost:5601"
  # Indices are created from a template (see output.elasticsearch.index). The following settings are to replace the index_name in the template.
  # Name of index to which the agent should send the block data
  blockIndexName: block
  # Name of index to which the agent should send the transaction data
  transactionIndexName: transaction
  # Name of index to which the agent should send the key data
  keyIndexName: key
  # Folder which should contain the generated dashboards. Note: this directory is going to be erased.
  dashboardDirectory: ${GOPATH}/src/github.com/hyperledger-elastic/dashboards/7/dashboard
  # Folder which contains the templates for Kibana objects (index patterns, dashboards, etc.)
  templateDirectory: ${GOPATH}/src/github.com/hyperledger-elastic/agent/kibana_templates

  chaincodes:
    # This is the name of the key that links transactions together (e.g. previous_key, link_key, etc.).
    - linkingkey: previousKey
      name: dummycc
      values: [hash]
    - name: fabcar
      linkingkey:
      values: ["make", "model", "colour", "owner"]

#-------------------------- Elasticsearch output ------------------------------
setup.ilm.enabled: false

output.elasticsearch.index: fabricbeat-%{[agent.version]}-%{[index_name]}-org${ORG_NUMBER}
output.elasticsearch.hosts: ["localhost:9200"]

setup.template.name: fabricbeat-%{[agent.version]}
setup.template.pattern: fabricbeat-%{[agent.version]}*

setup.dashboards.directory: ${GOPATH}/src/github.com/hyperledger-elastic/dashboards
